package model;
// Generated 20.May.2018 22:48:23 by Hibernate Tools 4.3.1



/**
 * Ogrenci generated by hbm2java
 */
public class Ogrenci  implements java.io.Serializable {


     private int ogrenciid;
     private String adSoyad;
     private String sehir;
     private String tel;

    public Ogrenci() {
    }

	
    public Ogrenci(int ogrenciid) {
        this.ogrenciid = ogrenciid;
    }
    public Ogrenci(int ogrenciid, String adSoyad, String sehir, String tel) {
       this.ogrenciid = ogrenciid;
       this.adSoyad = adSoyad;
       this.sehir = sehir;
       this.tel = tel;
    }
   
    public int getOgrenciid() {
        return this.ogrenciid;
    }
    
    public void setOgrenciid(int ogrenciid) {
        this.ogrenciid = ogrenciid;
    }
    public String getAdSoyad() {
        return this.adSoyad;
    }
    
    public void setAdSoyad(String adSoyad) {
        this.adSoyad = adSoyad;
    }
    public String getSehir() {
        return this.sehir;
    }
    
    public void setSehir(String sehir) {
        this.sehir = sehir;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }




}


